package KioskMain;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author admin
 */
public class SelectOrder extends javax.swing.JFrame {

    private final String orderType;
    private Connection conn;
    private MenuSQL menuRepository;

    public SelectOrder() {
        this("Dine In");
    }

    public SelectOrder(String orderType) {
        this.orderType = orderType;
        initComponents();
        pics();
    }

    private void pics() {
        setLocationRelativeTo(null);

        conn = database.connectdatabase();
        menuRepository = new MenuSQL(conn);

        panelMenu.setLayout(new java.awt.GridLayout(0, 2, 10, 10));
        steplbl2.setText(orderType);
        steplbl.setText(orderType);

        ImageSize.setFillImage(band, "Images/christmas.png");
        ImageSize.setFillImage(lbllogo2, "Images/Logo.png");
        
        loadWhatsNew();
        
    }

    private boolean hasConnection() {
        if (conn == null) {
            JOptionPane.showMessageDialog(this, "Database connection failed.");
            return false;
        }
        return true;
    }

    private void clearMenu() {
        panelMenu.removeAll();
        panelMenu.revalidate();
        panelMenu.repaint();
    }

    private void addMenuItem(MenuItemData item) {
        panelMenu.add(new MenuPanel(
                item.getId(),
                item.getName(),
                item.getPrice(),
                item.getImagePath()
        ));
    }

    private void displayItems(String title, List<MenuItemData> items) {
        clearMenu();
        lblCategory.setText(title);

        for (MenuItemData item : items) {
            addMenuItem(item);
        }

        panelMenu.revalidate();
        panelMenu.repaint();
    }

    private void showLoadError(String title, SQLException e) {
        JOptionPane.showMessageDialog(this, "Error loading " + title + ": " + e.getMessage());
    }

    private void loadWhatsNew() {
        loadCategory(1001, "What's New");
    }

    private void loadChicken() {
        loadCategory(1002, "Chicken");
    }

    private void loadPasta() {
        loadCategory(1003, "Pasta");
    }

    private void loadBurgers() {
        loadCategory(1004, "Burgers");
    }

    private void loadDesserts() {
        loadCategory(1005, "Desserts");
    }

    private void loadCategory(int categoryId, String categoryTitle) {
        if (!hasConnection()) {
            return;
        }

        try {
            displayItems(categoryTitle, menuRepository.findByCategoryId(categoryId));
        } catch (SQLException e) {
            showLoadError(categoryTitle, e);
        }
    }

    private void loadDrinks() {
        if (!hasConnection()) {
            return;
        }

        try {
            displayItems("Drinks", menuRepository.findDrinks());
        } catch (SQLException e) {
            showLoadError("Drinks", e);
        }
    }

    private void loadAddons() {
        if (!hasConnection()) {
            return;
        }

        try {
            displayItems("Add Ons", menuRepository.findAddons());
        } catch (SQLException e) {
            showLoadError("Add Ons", e);
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        steplbl = new javax.swing.JLabel();
        panelCategories = new javax.swing.JPanel();
        btnwhatsnew = new javax.swing.JButton();
        btnchicken = new javax.swing.JButton();
        btnpasta = new javax.swing.JButton();
        btnburger = new javax.swing.JButton();
        btndrink = new javax.swing.JButton();
        btndessert = new javax.swing.JButton();
        btnaddons = new javax.swing.JButton();
        lbllogo2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblCategory1 = new javax.swing.JLabel();
        lblCategory2 = new javax.swing.JLabel();
        lblCategory3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        band = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblCategory = new javax.swing.JLabel();
        panelScroll = new javax.swing.JScrollPane();
        panelMenu = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        steplbl2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(171, 48, 61));
        jPanel3.setPreferredSize(new java.awt.Dimension(105, 50));
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Step 1");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(30, 10, 89, 16);

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Step 2");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(140, 10, 89, 16);

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Select Order");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(140, 20, 89, 20);

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Step 2");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(270, 10, 89, 16);

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Payment");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(270, 20, 89, 20);

        jLabel8.setFont(new java.awt.Font("Arial Narrow", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Step 3");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(390, 10, 89, 16);

        jLabel9.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Checkout");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(390, 20, 89, 20);

        jPanel7.setBackground(new java.awt.Color(255, 204, 18));
        jPanel7.setPreferredSize(new java.awt.Dimension(100, 3));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel7);
        jPanel7.setBounds(128, 45, 100, 4);

        steplbl.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        steplbl.setForeground(new java.awt.Color(255, 255, 255));
        steplbl.setText("Dine In");
        jPanel3.add(steplbl);
        steplbl.setBounds(30, 20, 89, 20);

        panelCategories.setBackground(new java.awt.Color(255, 255, 255));

        btnwhatsnew.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        btnwhatsnew.setForeground(new java.awt.Color(171, 48, 61));
        btnwhatsnew.setText("What's New");
        btnwhatsnew.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(171, 48, 61), 2));
        btnwhatsnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnwhatsnewActionPerformed(evt);
            }
        });

        btnchicken.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        btnchicken.setForeground(new java.awt.Color(171, 48, 61));
        btnchicken.setText("Chicken");
        btnchicken.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(171, 48, 61), 2));
        btnchicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchickenActionPerformed(evt);
            }
        });

        btnpasta.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        btnpasta.setForeground(new java.awt.Color(171, 48, 61));
        btnpasta.setText("Pasta");
        btnpasta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(171, 48, 61), 2));
        btnpasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpastaActionPerformed(evt);
            }
        });

        btnburger.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        btnburger.setForeground(new java.awt.Color(171, 48, 61));
        btnburger.setText("Burger");
        btnburger.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(171, 48, 61), 2));
        btnburger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnburgerActionPerformed(evt);
            }
        });

        btndrink.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        btndrink.setForeground(new java.awt.Color(171, 48, 61));
        btndrink.setText("Drink");
        btndrink.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(171, 48, 61), 2));
        btndrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndrinkActionPerformed(evt);
            }
        });

        btndessert.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        btndessert.setForeground(new java.awt.Color(171, 48, 61));
        btndessert.setText("Dessert");
        btndessert.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(171, 48, 61), 2));
        btndessert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndessertActionPerformed(evt);
            }
        });

        btnaddons.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        btnaddons.setForeground(new java.awt.Color(171, 48, 61));
        btnaddons.setText("Add ons");
        btnaddons.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(171, 48, 61), 2));
        btnaddons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddonsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCategoriesLayout = new javax.swing.GroupLayout(panelCategories);
        panelCategories.setLayout(panelCategoriesLayout);
        panelCategoriesLayout.setHorizontalGroup(
            panelCategoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCategoriesLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(panelCategoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnwhatsnew, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(btnchicken, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(btnpasta, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(btnburger, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(btndrink, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(btndessert, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(btnaddons, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(lbllogo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelCategoriesLayout.setVerticalGroup(
            panelCategoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCategoriesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbllogo2, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnwhatsnew, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnchicken, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnpasta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnburger, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btndrink, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btndessert, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnaddons, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCategory1.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        lblCategory1.setText("Item Total");
        jPanel6.add(lblCategory1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 16, -1, -1));

        lblCategory2.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        lblCategory2.setText("Total");
        jPanel6.add(lblCategory2, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 6, -1, -1));

        lblCategory3.setFont(new java.awt.Font("Arial Narrow", 1, 22)); // NOI18N
        lblCategory3.setText("00.00");
        jPanel6.add(lblCategory3, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 33, -1, -1));

        jButton2.setBackground(new java.awt.Color(171, 48, 61));
        jButton2.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("VIEW ORDER");
        jButton2.setBorder(null);
        jPanel6.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 159, 39));

        jButton1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(171, 48, 61));
        jButton1.setText("CANCEL");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(171, 48, 61), 2));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 159, 39));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        lblCategory.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        lblCategory.setForeground(new java.awt.Color(171, 48, 61));
        lblCategory.setText("What's New");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelScroll.setBackground(new java.awt.Color(255, 255, 255));
        panelScroll.setBorder(null);
        panelScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        panelScroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        panelScroll.setViewportView(panelMenu);

        panelMenu.setBackground(new java.awt.Color(255, 255, 255));
        panelMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelMenu.setMaximumSize(new java.awt.Dimension(363, 486));
        panelMenu.setMinimumSize(new java.awt.Dimension(363, 486));
        panelMenu.setLayout(new java.awt.GridLayout(0, 2, 10, 10));
        panelScroll.setViewportView(panelMenu);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(255, 204, 18));

        steplbl2.setFont(new java.awt.Font("Arial Narrow", 1, 20)); // NOI18N
        steplbl2.setForeground(new java.awt.Color(255, 255, 255));
        steplbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        steplbl2.setText("Dine In");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(steplbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(steplbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
            .addComponent(band, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(panelCategories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(panelScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(band, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelCategories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 800));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddonsActionPerformed
        loadAddons();
    }//GEN-LAST:event_btnaddonsActionPerformed

    private void btndessertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndessertActionPerformed
        // TODO add your handling code here:
        loadDesserts();
    }//GEN-LAST:event_btndessertActionPerformed

    private void btndrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndrinkActionPerformed
        // TODO add your handling code here:
        loadDrinks();
    }//GEN-LAST:event_btndrinkActionPerformed

    private void btnburgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnburgerActionPerformed
        // TODO add your handling code here:
        loadBurgers();
    }//GEN-LAST:event_btnburgerActionPerformed

    private void btnpastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpastaActionPerformed
        // TODO add your handling code here:
        loadPasta();
    }//GEN-LAST:event_btnpastaActionPerformed

    private void btnchickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchickenActionPerformed
        // TODO add your handling code here:
        loadChicken();
    }//GEN-LAST:event_btnchickenActionPerformed

    private void btnwhatsnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnwhatsnewActionPerformed
        // TODO add your handling code here:
        loadWhatsNew();
    }//GEN-LAST:event_btnwhatsnewActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel band;
    private javax.swing.JButton btnaddons;
    private javax.swing.JButton btnburger;
    private javax.swing.JButton btnchicken;
    private javax.swing.JButton btndessert;
    private javax.swing.JButton btndrink;
    private javax.swing.JButton btnpasta;
    private javax.swing.JButton btnwhatsnew;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblCategory1;
    private javax.swing.JLabel lblCategory2;
    private javax.swing.JLabel lblCategory3;
    private javax.swing.JLabel lbllogo2;
    private javax.swing.JPanel panelCategories;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JScrollPane panelScroll;
    private javax.swing.JLabel steplbl;
    private javax.swing.JLabel steplbl2;
    // End of variables declaration//GEN-END:variables
}
