/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jakob
 */
public class AdminMain extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminMain.class.getName());
    
    ImageIcon icon = new ImageIcon("images/KioskIcon.png");
    Image kioskIcon = icon.getImage();
    
    //SQL
    Connection conn;
    Statement stmt;
    PreparedStatement ps;
    ResultSet rs;
    
    ImageIcon image = new ImageIcon("Images/Logo.png");
    Image scaledImage = image.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH);
    ImageIcon resizedImage = new ImageIcon(scaledImage);
    
    private String userRole;
    PayOrder po;

    public AdminMain(String userRole) {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setIconImage(kioskIcon);
        setTitle("Fast Food");
        conn = DatabaseConnection.connectDatabase(); //SQL Connection
        po = new PayOrder(conn, this);
        logoHolder.setIcon(resizedImage);
        
        this.userRole = userRole;
        setupRolePermissions();
        enableButtons();
        mainCreateOrderPanel.setLayout(new WrapLayout(FlowLayout.LEFT, 15, 15));


        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        logoHolder = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        createOrderButton = new javax.swing.JButton();
        payOrderButton = new javax.swing.JButton();
        orderLogsButton = new javax.swing.JButton();
        editMenuButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        logoutButton = new javax.swing.JButton();
        mainCardPanel = new javax.swing.JPanel();
        payOrderPanel = new javax.swing.JPanel();
        orderNumTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        orderNumButton = new javax.swing.JButton();
        calculateButton = new javax.swing.JButton();
        paymentTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        addOrderButton = new javax.swing.JButton();
        editOrderButton = new javax.swing.JButton();
        deleteButtonOrder = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        discountComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        totalPriceLabel = new javax.swing.JLabel();
        createOrderPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        createWNButton = new javax.swing.JButton();
        createCButton = new javax.swing.JButton();
        createPButton = new javax.swing.JButton();
        creatBButton = new javax.swing.JButton();
        createDesButton = new javax.swing.JButton();
        createDrinkButton = new javax.swing.JButton();
        creatAOButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableCreateOrder = new javax.swing.JTable();
        decreaseQuanCreateOrderButton = new javax.swing.JButton();
        increaseQuanCreateOrderButton = new javax.swing.JButton();
        removeButtonCreateOrder = new javax.swing.JButton();
        clearButtonCreateOrder = new javax.swing.JButton();
        confirmOrderCreateOrderButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        totalAmountLabel = new javax.swing.JLabel();
        discountCreateOrderComboBox = new javax.swing.JComboBox<>();
        mainCreateOrderPanel = new javax.swing.JPanel();
        paymentCOTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        editMenuPanel = new javax.swing.JPanel();
        orderLogsPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 214, 102));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setDoubleBuffered(false);

        sidePanel.setBackground(new java.awt.Color(243, 93, 93));

        logoHolder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jPanel3.setBackground(new java.awt.Color(243, 93, 93));

        createOrderButton.setBackground(new java.awt.Color(174, 54, 54));
        createOrderButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        createOrderButton.setForeground(new java.awt.Color(255, 255, 255));
        createOrderButton.setText("Create Order");
        createOrderButton.setBorder(null);
        createOrderButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createOrderButton.setFocusable(false);
        createOrderButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        createOrderButton.setMaximumSize(new java.awt.Dimension(36, 28));
        createOrderButton.setMinimumSize(new java.awt.Dimension(36, 28));
        createOrderButton.setPreferredSize(new java.awt.Dimension(36, 28));
        createOrderButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                createOrderButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                createOrderButtonMouseExited(evt);
            }
        });
        createOrderButton.addActionListener(this::createOrderButtonActionPerformed);

        payOrderButton.setBackground(new java.awt.Color(174, 54, 54));
        payOrderButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        payOrderButton.setForeground(new java.awt.Color(255, 255, 255));
        payOrderButton.setText("Pay Order");
        payOrderButton.setBorder(null);
        payOrderButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        payOrderButton.setFocusPainted(false);
        payOrderButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        payOrderButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                payOrderButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                payOrderButtonMouseExited(evt);
            }
        });
        payOrderButton.addActionListener(this::payOrderButtonActionPerformed);

        orderLogsButton.setBackground(new java.awt.Color(174, 54, 54));
        orderLogsButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        orderLogsButton.setForeground(new java.awt.Color(255, 255, 255));
        orderLogsButton.setText("Order Logs");
        orderLogsButton.setBorder(null);
        orderLogsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        orderLogsButton.setFocusable(false);
        orderLogsButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        orderLogsButton.setMaximumSize(new java.awt.Dimension(36, 28));
        orderLogsButton.setMinimumSize(new java.awt.Dimension(36, 28));
        orderLogsButton.setPreferredSize(new java.awt.Dimension(36, 28));
        orderLogsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                orderLogsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                orderLogsButtonMouseExited(evt);
            }
        });
        orderLogsButton.addActionListener(this::orderLogsButtonActionPerformed);

        editMenuButton.setBackground(new java.awt.Color(174, 54, 54));
        editMenuButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        editMenuButton.setForeground(new java.awt.Color(255, 255, 255));
        editMenuButton.setText("Edit Menu");
        editMenuButton.setBorder(null);
        editMenuButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editMenuButton.setFocusable(false);
        editMenuButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        editMenuButton.setMaximumSize(new java.awt.Dimension(36, 28));
        editMenuButton.setMinimumSize(new java.awt.Dimension(36, 28));
        editMenuButton.setPreferredSize(new java.awt.Dimension(36, 28));
        editMenuButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editMenuButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editMenuButtonMouseExited(evt);
            }
        });
        editMenuButton.addActionListener(this::editMenuButtonActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(orderLogsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(payOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(editMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(payOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderLogsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(153, 214, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 5));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        logoutButton.setBackground(new java.awt.Color(174, 54, 54));
        logoutButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Log Out");
        logoutButton.setBorder(null);
        logoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutButton.setFocusable(false);
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutButtonMouseExited(evt);
            }
        });
        logoutButton.addActionListener(this::logoutButtonActionPerformed);

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(logoHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(logoHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        mainCardPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainCardPanel.setLayout(new java.awt.CardLayout());

        payOrderPanel.setBackground(new java.awt.Color(235, 235, 235));

        orderNumTextField.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        orderNumTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 93, 93), 4));

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel1.setText("Enter Order Number:");

        orderNumButton.setBackground(new java.awt.Color(243, 93, 93));
        orderNumButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        orderNumButton.setForeground(new java.awt.Color(255, 255, 255));
        orderNumButton.setText("Enter");
        orderNumButton.setBorder(null);
        orderNumButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        orderNumButton.setFocusPainted(false);
        orderNumButton.addActionListener(this::orderNumButtonActionPerformed);

        calculateButton.setBackground(new java.awt.Color(122, 255, 89));
        calculateButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        calculateButton.setForeground(new java.awt.Color(51, 51, 51));
        calculateButton.setText("Calculate");
        calculateButton.setAutoscrolls(true);
        calculateButton.setBorder(null);
        calculateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calculateButton.setFocusable(false);
        calculateButton.addActionListener(this::calculateButtonActionPerformed);

        paymentTextField.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        paymentTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 93, 93), 4));

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel3.setText("Enter Payment Amount:");

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Item", "Drinks", "Add-ons", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderTable.setShowGrid(false);
        jScrollPane2.setViewportView(orderTable);
        if (orderTable.getColumnModel().getColumnCount() > 0) {
            orderTable.getColumnModel().getColumn(0).setResizable(false);
            orderTable.getColumnModel().getColumn(1).setResizable(false);
            orderTable.getColumnModel().getColumn(2).setResizable(false);
            orderTable.getColumnModel().getColumn(3).setResizable(false);
            orderTable.getColumnModel().getColumn(4).setResizable(false);
        }

        addOrderButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        addOrderButton.setForeground(new java.awt.Color(243, 93, 93));
        addOrderButton.setText("Add");
        addOrderButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 102), 3));
        addOrderButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addOrderButton.setFocusable(false);
        addOrderButton.setRequestFocusEnabled(false);
        addOrderButton.addActionListener(this::addOrderButtonActionPerformed);

        editOrderButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        editOrderButton.setForeground(new java.awt.Color(243, 93, 93));
        editOrderButton.setText("Edit");
        editOrderButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 3));
        editOrderButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editOrderButton.addActionListener(this::editOrderButtonActionPerformed);

        deleteButtonOrder.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        deleteButtonOrder.setForeground(new java.awt.Color(243, 93, 93));
        deleteButtonOrder.setText("Delete");
        deleteButtonOrder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102), 3));
        deleteButtonOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteButtonOrder.addActionListener(this::deleteButtonOrderActionPerformed);

        jLabel4.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(243, 93, 93));
        jLabel4.setText("Total Price: ");

        discountComboBox.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        discountComboBox.setForeground(new java.awt.Color(243, 93, 93));
        discountComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Senior Discount", "PWD" }));
        discountComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 93, 93), 3));
        discountComboBox.addActionListener(this::discountComboBoxActionPerformed);

        jLabel5.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(243, 93, 93));
        jLabel5.setText("Select Discount:");

        totalPriceLabel.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        totalPriceLabel.setForeground(new java.awt.Color(243, 93, 93));
        totalPriceLabel.setText(" ");

        javax.swing.GroupLayout payOrderPanelLayout = new javax.swing.GroupLayout(payOrderPanel);
        payOrderPanel.setLayout(payOrderPanelLayout);
        payOrderPanelLayout.setHorizontalGroup(
            payOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payOrderPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(payOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(payOrderPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalPriceLabel))
                    .addGroup(payOrderPanelLayout.createSequentialGroup()
                        .addGroup(payOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(payOrderPanelLayout.createSequentialGroup()
                                .addComponent(orderNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(orderNumButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addGap(23, 23, 23)
                        .addGroup(payOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(payOrderPanelLayout.createSequentialGroup()
                                .addComponent(paymentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, payOrderPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(payOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addOrderButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editOrderButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, payOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(deleteButtonOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(discountComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 130, Short.MAX_VALUE))
        );
        payOrderPanelLayout.setVerticalGroup(
            payOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payOrderPanelLayout.createSequentialGroup()
                .addGroup(payOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(payOrderPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)
                        .addGroup(payOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(orderNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(orderNumButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(payOrderPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel3)
                        .addGap(7, 7, 7)
                        .addGroup(payOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(paymentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(payOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(payOrderPanelLayout.createSequentialGroup()
                        .addComponent(addOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(editOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(deleteButtonOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(discountComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(payOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(totalPriceLabel))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        mainCardPanel.add(payOrderPanel, "payOrderCard");

        createOrderPanel.setBackground(new java.awt.Color(235, 235, 235));

        jPanel5.setBackground(new java.awt.Color(235, 235, 235));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        createWNButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        createWNButton.setForeground(new java.awt.Color(243, 93, 93));
        createWNButton.setText("What's New");
        createWNButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 93, 93), 3));
        createWNButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createWNButton.addActionListener(this::createWNButtonActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(9, 14, 0, 6);
        jPanel5.add(createWNButton, gridBagConstraints);

        createCButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        createCButton.setForeground(new java.awt.Color(243, 93, 93));
        createCButton.setText("Chicken");
        createCButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 93, 93), 3));
        createCButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createCButton.addActionListener(this::createCButtonActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(9, 1, 0, 12);
        jPanel5.add(createCButton, gridBagConstraints);

        createPButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        createPButton.setForeground(new java.awt.Color(243, 93, 93));
        createPButton.setText("Pasta");
        createPButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 93, 93), 3));
        createPButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createPButton.addActionListener(this::createPButtonActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 47;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(9, 1, 0, 12);
        jPanel5.add(createPButton, gridBagConstraints);

        creatBButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        creatBButton.setForeground(new java.awt.Color(243, 93, 93));
        creatBButton.setText("Burgers");
        creatBButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 93, 93), 3));
        creatBButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        creatBButton.addActionListener(this::creatBButtonActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(9, 1, 0, 12);
        jPanel5.add(creatBButton, gridBagConstraints);

        createDesButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        createDesButton.setForeground(new java.awt.Color(243, 93, 93));
        createDesButton.setText("Dessert");
        createDesButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 93, 93), 3));
        createDesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createDesButton.addActionListener(this::createDesButtonActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(9, 1, 0, 12);
        jPanel5.add(createDesButton, gridBagConstraints);

        createDrinkButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        createDrinkButton.setForeground(new java.awt.Color(243, 93, 93));
        createDrinkButton.setText("Drinks");
        createDrinkButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 93, 93), 3));
        createDrinkButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createDrinkButton.addActionListener(this::createDrinkButtonActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(9, 6, 9, 0);
        jPanel5.add(createDrinkButton, gridBagConstraints);

        creatAOButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        creatAOButton.setForeground(new java.awt.Color(243, 93, 93));
        creatAOButton.setText("Add-ons");
        creatAOButton.setToolTipText("");
        creatAOButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 93, 93), 3));
        creatAOButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        creatAOButton.addActionListener(this::creatAOButtonActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(9, 0, 9, 12);
        jPanel5.add(creatAOButton, gridBagConstraints);

        tableCreateOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Item", "Quantity", "Price", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableCreateOrder);
        if (tableCreateOrder.getColumnModel().getColumnCount() > 0) {
            tableCreateOrder.getColumnModel().getColumn(0).setResizable(false);
            tableCreateOrder.getColumnModel().getColumn(1).setResizable(false);
            tableCreateOrder.getColumnModel().getColumn(2).setResizable(false);
            tableCreateOrder.getColumnModel().getColumn(3).setResizable(false);
        }

        decreaseQuanCreateOrderButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        decreaseQuanCreateOrderButton.setForeground(new java.awt.Color(243, 93, 93));
        decreaseQuanCreateOrderButton.setText("Decrease");
        decreaseQuanCreateOrderButton.setToolTipText("");
        decreaseQuanCreateOrderButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 93, 93), 3));
        decreaseQuanCreateOrderButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        decreaseQuanCreateOrderButton.addActionListener(this::decreaseQuanCreateOrderButtonActionPerformed);

        increaseQuanCreateOrderButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        increaseQuanCreateOrderButton.setForeground(new java.awt.Color(243, 93, 93));
        increaseQuanCreateOrderButton.setText("Increase");
        increaseQuanCreateOrderButton.setToolTipText("");
        increaseQuanCreateOrderButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 93, 93), 3));
        increaseQuanCreateOrderButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        increaseQuanCreateOrderButton.addActionListener(this::increaseQuanCreateOrderButtonActionPerformed);

        removeButtonCreateOrder.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        removeButtonCreateOrder.setForeground(new java.awt.Color(243, 93, 93));
        removeButtonCreateOrder.setText("Remove");
        removeButtonCreateOrder.setToolTipText("");
        removeButtonCreateOrder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 93, 93), 3));
        removeButtonCreateOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeButtonCreateOrder.addActionListener(this::removeButtonCreateOrderActionPerformed);

        clearButtonCreateOrder.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        clearButtonCreateOrder.setForeground(new java.awt.Color(243, 93, 93));
        clearButtonCreateOrder.setText("Cancel/Clear");
        clearButtonCreateOrder.setToolTipText("");
        clearButtonCreateOrder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 93, 93), 3));
        clearButtonCreateOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearButtonCreateOrder.addActionListener(this::clearButtonCreateOrderActionPerformed);

        confirmOrderCreateOrderButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        confirmOrderCreateOrderButton.setForeground(new java.awt.Color(243, 93, 93));
        confirmOrderCreateOrderButton.setText("Confirm Order");
        confirmOrderCreateOrderButton.setToolTipText("");
        confirmOrderCreateOrderButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 102), 3));
        confirmOrderCreateOrderButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        confirmOrderCreateOrderButton.addActionListener(this::confirmOrderCreateOrderButtonActionPerformed);

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(243, 93, 93));
        jLabel2.setText("Total Amount:");

        totalAmountLabel.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        totalAmountLabel.setForeground(new java.awt.Color(243, 93, 93));
        totalAmountLabel.setText(" ");

        discountCreateOrderComboBox.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        discountCreateOrderComboBox.setForeground(new java.awt.Color(243, 93, 93));
        discountCreateOrderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Senior Discount", "PWD" }));
        discountCreateOrderComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 93, 93), 3));
        discountCreateOrderComboBox.addActionListener(this::discountCreateOrderComboBoxActionPerformed);

        javax.swing.GroupLayout mainCreateOrderPanelLayout = new javax.swing.GroupLayout(mainCreateOrderPanel);
        mainCreateOrderPanel.setLayout(mainCreateOrderPanelLayout);
        mainCreateOrderPanelLayout.setHorizontalGroup(
            mainCreateOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );
        mainCreateOrderPanelLayout.setVerticalGroup(
            mainCreateOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        paymentCOTextField.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        paymentCOTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 93, 93), 3));

        jLabel6.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(243, 93, 93));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Payment:");

        javax.swing.GroupLayout createOrderPanelLayout = new javax.swing.GroupLayout(createOrderPanel);
        createOrderPanel.setLayout(createOrderPanelLayout);
        createOrderPanelLayout.setHorizontalGroup(
            createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createOrderPanelLayout.createSequentialGroup()
                .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainCreateOrderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(createOrderPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(createOrderPanelLayout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paymentCOTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(createOrderPanelLayout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(totalAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createOrderPanelLayout.createSequentialGroup()
                            .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(createOrderPanelLayout.createSequentialGroup()
                                    .addComponent(decreaseQuanCreateOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(increaseQuanCreateOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(removeButtonCreateOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(createOrderPanelLayout.createSequentialGroup()
                                    .addComponent(clearButtonCreateOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(discountCreateOrderComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGap(1, 1, 1)))
                    .addComponent(confirmOrderCreateOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        createOrderPanelLayout.setVerticalGroup(
            createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createOrderPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(createOrderPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(totalAmountLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(decreaseQuanCreateOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(increaseQuanCreateOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removeButtonCreateOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clearButtonCreateOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(discountCreateOrderComboBox)))
                    .addGroup(createOrderPanelLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mainCreateOrderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createOrderPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(confirmOrderCreateOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                            .addComponent(paymentCOTextField)))
                    .addGroup(createOrderPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel6)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        mainCardPanel.add(createOrderPanel, "createOrderCard");

        editMenuPanel.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout editMenuPanelLayout = new javax.swing.GroupLayout(editMenuPanel);
        editMenuPanel.setLayout(editMenuPanelLayout);
        editMenuPanelLayout.setHorizontalGroup(
            editMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1068, Short.MAX_VALUE)
        );
        editMenuPanelLayout.setVerticalGroup(
            editMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
        );

        mainCardPanel.add(editMenuPanel, "editMenuCard");

        orderLogsPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout orderLogsPanelLayout = new javax.swing.GroupLayout(orderLogsPanel);
        orderLogsPanel.setLayout(orderLogsPanelLayout);
        orderLogsPanelLayout.setHorizontalGroup(
            orderLogsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1068, Short.MAX_VALUE)
        );
        orderLogsPanelLayout.setVerticalGroup(
            orderLogsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
        );

        mainCardPanel.add(orderLogsPanel, "orderLogsCard");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(mainCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadMenuItems(String categoryName) {
        mainCreateOrderPanel.removeAll();

        try {
            String query = """
                SELECT m.itemID, m.itemName, m.price, m.imagePath
                FROM menu_items m
                JOIN categories c ON m.categoryId = c.categoryId
                WHERE c.categoryName = ?
            """;

            ps = conn.prepareStatement(query);
            ps.setString(1, categoryName);
            rs = ps.executeQuery();

            while (rs.next()) {
                String name = rs.getString("itemName");
                double price = rs.getDouble("price");
                String imagePath = rs.getString("imagePath");
                int itemId = rs.getInt("itemID");

                MenuCard card = new MenuCard(
                    itemId,
                    name,
                    price,
                    imagePath
                );
                mainCreateOrderPanel.add(card);
            }

            mainCreateOrderPanel.revalidate();
            mainCreateOrderPanel.repaint();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void loadDrinks() {
        mainCreateOrderPanel.removeAll();

        try {
            String query = "SELECT * FROM drinks";
            ps = conn.prepareStatement(query);
            rs = ps.executeQuery();

            while (rs.next()) {
                int drinkId = rs.getInt("drinkID");
                
                MenuCard card = new MenuCard(
                    drinkId,
                    rs.getString("drinkName"),
                    rs.getDouble("price"),
                    rs.getString("image_path")
                );
                mainCreateOrderPanel.add(card);
            }

            mainCreateOrderPanel.revalidate();
            mainCreateOrderPanel.repaint();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void loadAddOns() {
        mainCreateOrderPanel.removeAll();

        try {
            String query = "SELECT * FROM add_ons";
            ps = conn.prepareStatement(query);
            rs = ps.executeQuery();

            while (rs.next()) {
                int addonId = rs.getInt("addonId");

                MenuCard card = new MenuCard(
                    addonId,
                    rs.getString("addonName"),
                    rs.getDouble("price"),
                    rs.getString("imagePath")
                );
                mainCreateOrderPanel.add(card);
            }

            mainCreateOrderPanel.revalidate();
            mainCreateOrderPanel.repaint();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void setupRolePermissions() {
        if ("admin".equalsIgnoreCase(userRole)) {
            editMenuButton.setEnabled(true);
            orderLogsButton.setEnabled(true);
            payOrderButton.setEnabled(true);
            createOrderButton.setEnabled(true);
        } else if ("cashier".equalsIgnoreCase(userRole)) {
            editMenuButton.setEnabled(false);
            orderLogsButton.setEnabled(false);
            payOrderButton.setEnabled(true);
            createOrderButton.setEnabled(true);
            
            orderLogsButton.setBackground(new Color(173, 68, 68));
            editMenuButton.setBackground(new Color(173, 68, 68));
        }
    }
    
    private void enableButtons(){
        if(po.currentOrderId == 0){
            calculateButton.setEnabled(false);
            addOrderButton.setEnabled(false);
            editOrderButton.setEnabled(false);
            deleteButtonOrder.setEnabled(false);
            discountComboBox.setEnabled(false);
        }else{
            calculateButton.setEnabled(true);
            addOrderButton.setEnabled(true);
            editOrderButton.setEnabled(true);
            deleteButtonOrder.setEnabled(true);
            discountComboBox.setEnabled(true);
        }
    }
    
    private void payOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payOrderButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainCardPanel.getLayout();
        card.show(mainCardPanel, "payOrderCard");
        payOrderButton.setBackground(new Color(150, 47, 47));
    }//GEN-LAST:event_payOrderButtonActionPerformed

    private void payOrderButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payOrderButtonMouseExited
        // TODO add your handling code here:
        payOrderButton.setBackground(new Color(174,54,54));
    }//GEN-LAST:event_payOrderButtonMouseExited

    private void payOrderButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payOrderButtonMouseEntered
        // TODO add your handling code here:
        payOrderButton.setBackground(new Color(150, 47, 47));
    }//GEN-LAST:event_payOrderButtonMouseEntered

    private void createOrderButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createOrderButtonMouseEntered
        // TODO add your handling code here:
        createOrderButton.setBackground(new Color(150, 47, 47));
    }//GEN-LAST:event_createOrderButtonMouseEntered

    private void createOrderButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createOrderButtonMouseExited
        // TODO add your handling code here:
        createOrderButton.setBackground(new Color(174,54,54));
    }//GEN-LAST:event_createOrderButtonMouseExited

    private void orderLogsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderLogsButtonMouseEntered
        // TODO add your handling code here:
        if (orderLogsButton.isEnabled()) {
            orderLogsButton.setBackground(new Color(150, 47, 47));
        }
    }//GEN-LAST:event_orderLogsButtonMouseEntered

    private void orderLogsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderLogsButtonMouseExited
        // TODO add your handling code here:
        if (orderLogsButton.isEnabled()) {
        orderLogsButton.setBackground(new Color(174,54,54));
        }
    }//GEN-LAST:event_orderLogsButtonMouseExited

    private void editMenuButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMenuButtonMouseEntered
        // TODO add your handling code here:
        if(editMenuButton.isEnabled()){
        editMenuButton.setBackground(new Color(150, 47, 47));
        }
    }//GEN-LAST:event_editMenuButtonMouseEntered

    private void editMenuButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMenuButtonMouseExited
        // TODO add your handling code here:
        if(editMenuButton.isEnabled()){
        editMenuButton.setBackground(new Color(174,54,54));
        }
    }//GEN-LAST:event_editMenuButtonMouseExited

    private void logoutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseEntered
        // TODO add your handling code here:
        logoutButton.setBackground(new Color(150, 47, 47));
    }//GEN-LAST:event_logoutButtonMouseEntered

    private void logoutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseExited
        // TODO add your handling code here:
        logoutButton.setBackground(new Color(174,54,54));
    }//GEN-LAST:event_logoutButtonMouseExited

    private void orderLogsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderLogsButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainCardPanel.getLayout();
        card.show(mainCardPanel, "orderLogsCard");
    }//GEN-LAST:event_orderLogsButtonActionPerformed

    private void createOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createOrderButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainCardPanel.getLayout();
        card.show(mainCardPanel, "createOrderCard");
    }//GEN-LAST:event_createOrderButtonActionPerformed

    private void editMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMenuButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainCardPanel.getLayout();
        card.show(mainCardPanel, "editMenuCard");
    }//GEN-LAST:event_editMenuButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed

        po.calculateChange();
    }//GEN-LAST:event_calculateButtonActionPerformed

    private void createCButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCButtonActionPerformed
        // TODO add your handling code here:
        loadMenuItems("Chicken");
    }//GEN-LAST:event_createCButtonActionPerformed

    private void increaseQuanCreateOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_increaseQuanCreateOrderButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_increaseQuanCreateOrderButtonActionPerformed

    private void removeButtonCreateOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonCreateOrderActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_removeButtonCreateOrderActionPerformed

    private void addOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrderButtonActionPerformed
        // TODO add your handling code here:
        po.addOrderItem();

        
    }//GEN-LAST:event_addOrderButtonActionPerformed

    private void editOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editOrderButtonActionPerformed
        // TODO add your handling code here:
        po.editOrderItem();
    }//GEN-LAST:event_editOrderButtonActionPerformed

    private void deleteButtonOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonOrderActionPerformed
        // TODO add your handling code here:
        po.deleteOrderItem();
    }//GEN-LAST:event_deleteButtonOrderActionPerformed

    private void orderNumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderNumButtonActionPerformed
        // TODO add your handling code here:
        po.loadOrder();
        enableButtons();
    }//GEN-LAST:event_orderNumButtonActionPerformed

    private void discountComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountComboBoxActionPerformed
        // TODO add your handling code here:
        if (po.currentOrderId != 0) po.applyDiscount(); 
    }//GEN-LAST:event_discountComboBoxActionPerformed

    private void createWNButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createWNButtonActionPerformed
        // TODO add your handling code here:
        loadMenuItems("What's New");
    }//GEN-LAST:event_createWNButtonActionPerformed

    private void createPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPButtonActionPerformed
        // TODO add your handling code here:
        loadMenuItems("Pasta");
    }//GEN-LAST:event_createPButtonActionPerformed

    private void creatBButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creatBButtonActionPerformed
        // TODO add your handling code here:
        loadMenuItems("Burgers");
    }//GEN-LAST:event_creatBButtonActionPerformed

    private void createDesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDesButtonActionPerformed
        // TODO add your handling code here:
        loadMenuItems("Desserts");
    }//GEN-LAST:event_createDesButtonActionPerformed

    private void createDrinkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDrinkButtonActionPerformed
        // TODO add your handling code here:
        loadDrinks();
    }//GEN-LAST:event_createDrinkButtonActionPerformed

    private void creatAOButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creatAOButtonActionPerformed
        // TODO add your handling code here:
        loadAddOns();
    }//GEN-LAST:event_creatAOButtonActionPerformed

    private void decreaseQuanCreateOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decreaseQuanCreateOrderButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_decreaseQuanCreateOrderButtonActionPerformed

    private void clearButtonCreateOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonCreateOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearButtonCreateOrderActionPerformed

    private void discountCreateOrderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountCreateOrderComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discountCreateOrderComboBoxActionPerformed

    private void confirmOrderCreateOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmOrderCreateOrderButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmOrderCreateOrderButtonActionPerformed



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        String userRole = "admin";
        java.awt.EventQueue.invokeLater(() -> new AdminMain(userRole).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton addOrderButton;
    public javax.swing.JButton calculateButton;
    public javax.swing.JButton clearButtonCreateOrder;
    public javax.swing.JButton confirmOrderCreateOrderButton;
    public javax.swing.JButton creatAOButton;
    public javax.swing.JButton creatBButton;
    public javax.swing.JButton createCButton;
    public javax.swing.JButton createDesButton;
    public javax.swing.JButton createDrinkButton;
    public javax.swing.JButton createOrderButton;
    public javax.swing.JPanel createOrderPanel;
    public javax.swing.JButton createPButton;
    public javax.swing.JButton createWNButton;
    public javax.swing.JButton decreaseQuanCreateOrderButton;
    public javax.swing.JButton deleteButtonOrder;
    public javax.swing.JComboBox<String> discountComboBox;
    public javax.swing.JComboBox<String> discountCreateOrderComboBox;
    public javax.swing.JButton editMenuButton;
    public javax.swing.JPanel editMenuPanel;
    public javax.swing.JButton editOrderButton;
    public javax.swing.JButton increaseQuanCreateOrderButton;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JLabel logoHolder;
    public javax.swing.JButton logoutButton;
    public javax.swing.JPanel mainCardPanel;
    public javax.swing.JPanel mainCreateOrderPanel;
    public javax.swing.JButton orderLogsButton;
    public javax.swing.JPanel orderLogsPanel;
    public javax.swing.JButton orderNumButton;
    public javax.swing.JTextField orderNumTextField;
    public javax.swing.JTable orderTable;
    public javax.swing.JButton payOrderButton;
    public javax.swing.JPanel payOrderPanel;
    public javax.swing.JTextField paymentCOTextField;
    public javax.swing.JTextField paymentTextField;
    public javax.swing.JButton removeButtonCreateOrder;
    public javax.swing.JPanel sidePanel;
    public javax.swing.JTable tableCreateOrder;
    public javax.swing.JLabel totalAmountLabel;
    public javax.swing.JLabel totalPriceLabel;
    // End of variables declaration//GEN-END:variables
}
