/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jakob
 */
public class AdminMain extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminMain.class.getName());
    
    ImageIcon icon = new ImageIcon("images/KioskIcon.png");
    Image kioskIcon = icon.getImage();
    
    //SQL
    Connection conn;
    Statement stmt;
    PreparedStatement ps;
    ResultSet rs;
    
    ImageIcon image = new ImageIcon("Images/Logo.png");
    Image scaledImage = image.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH);
    ImageIcon resizedImage = new ImageIcon(scaledImage);
    
    private String userRole;

    // Pay Order state
    private int currentOrderId = 0;
    private double currentTotal = 0;
    private double currentFinalTotal = 0;
    private boolean currentOrderPaid = false;
    private final List<Integer> orderItemIds = new ArrayList<>();

    public AdminMain(String userRole) {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setIconImage(kioskIcon);
        setTitle("Fast Food");
        conn = DatabaseConnection.connectDatabase(); //SQL Connection
        logoHolder.setIcon(resizedImage);
        
        this.userRole = userRole;
        setupRolePermissions();

        // Wire pay-order panel buttons (not in GEN block)
        orderNumButton.addActionListener(e -> loadOrder());
        addOrderButton.addActionListener(e -> addOrderItem());
        editOrderButton.addActionListener(e -> editOrderItem());
        deleteButtonOrder.addActionListener(e -> deleteOrderItem());
        discountComboBox.addActionListener(e -> { if (currentOrderId != 0) applyDiscount(); });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        logoHolder = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        createOrderButton = new javax.swing.JButton();
        payOrderButton = new javax.swing.JButton();
        orderLogsButton = new javax.swing.JButton();
        editMenuButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        logoutButton = new javax.swing.JButton();
        mainCardPanel = new javax.swing.JPanel();
        payOrderPanel = new javax.swing.JPanel();
        orderNumTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        orderNumButton = new javax.swing.JButton();
        calculateButton = new javax.swing.JButton();
        paymentTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        addOrderButton = new javax.swing.JButton();
        editOrderButton = new javax.swing.JButton();
        deleteButtonOrder = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        discountComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        totalPriceLabel = new javax.swing.JLabel();
        createOrderPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        createWNButton = new javax.swing.JButton();
        createCButton = new javax.swing.JButton();
        createPButton = new javax.swing.JButton();
        creatBButton = new javax.swing.JButton();
        createDesButton = new javax.swing.JButton();
        createDrinkButton = new javax.swing.JButton();
        creatAOButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        decreaseQuanButton = new javax.swing.JButton();
        increaseQuanButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        confirmOrderButtonCO = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        totalAmountLabel = new javax.swing.JLabel();
        discountCOComboBox = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        editMenuPanel = new javax.swing.JPanel();
        orderLogsPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 214, 102));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setDoubleBuffered(false);

        sidePanel.setBackground(new java.awt.Color(243, 93, 93));

        logoHolder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jPanel3.setBackground(new java.awt.Color(243, 93, 93));

        createOrderButton.setBackground(new java.awt.Color(174, 54, 54));
        createOrderButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        createOrderButton.setForeground(new java.awt.Color(255, 255, 255));
        createOrderButton.setText("Create Order");
        createOrderButton.setBorder(null);
        createOrderButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createOrderButton.setFocusable(false);
        createOrderButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        createOrderButton.setMaximumSize(new java.awt.Dimension(36, 28));
        createOrderButton.setMinimumSize(new java.awt.Dimension(36, 28));
        createOrderButton.setPreferredSize(new java.awt.Dimension(36, 28));
        createOrderButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                createOrderButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                createOrderButtonMouseExited(evt);
            }
        });
        createOrderButton.addActionListener(this::createOrderButtonActionPerformed);

        payOrderButton.setBackground(new java.awt.Color(174, 54, 54));
        payOrderButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        payOrderButton.setForeground(new java.awt.Color(255, 255, 255));
        payOrderButton.setText("Pay Order");
        payOrderButton.setBorder(null);
        payOrderButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        payOrderButton.setFocusPainted(false);
        payOrderButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        payOrderButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                payOrderButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                payOrderButtonMouseExited(evt);
            }
        });
        payOrderButton.addActionListener(this::payOrderButtonActionPerformed);

        orderLogsButton.setBackground(new java.awt.Color(174, 54, 54));
        orderLogsButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        orderLogsButton.setForeground(new java.awt.Color(255, 255, 255));
        orderLogsButton.setText("Order Logs");
        orderLogsButton.setBorder(null);
        orderLogsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        orderLogsButton.setFocusable(false);
        orderLogsButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        orderLogsButton.setMaximumSize(new java.awt.Dimension(36, 28));
        orderLogsButton.setMinimumSize(new java.awt.Dimension(36, 28));
        orderLogsButton.setPreferredSize(new java.awt.Dimension(36, 28));
        orderLogsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                orderLogsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                orderLogsButtonMouseExited(evt);
            }
        });
        orderLogsButton.addActionListener(this::orderLogsButtonActionPerformed);

        editMenuButton.setBackground(new java.awt.Color(174, 54, 54));
        editMenuButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        editMenuButton.setForeground(new java.awt.Color(255, 255, 255));
        editMenuButton.setText("Edit Menu");
        editMenuButton.setBorder(null);
        editMenuButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editMenuButton.setFocusable(false);
        editMenuButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        editMenuButton.setMaximumSize(new java.awt.Dimension(36, 28));
        editMenuButton.setMinimumSize(new java.awt.Dimension(36, 28));
        editMenuButton.setPreferredSize(new java.awt.Dimension(36, 28));
        editMenuButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editMenuButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editMenuButtonMouseExited(evt);
            }
        });
        editMenuButton.addActionListener(this::editMenuButtonActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(orderLogsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(payOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(editMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(payOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderLogsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(153, 214, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 5));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        logoutButton.setBackground(new java.awt.Color(174, 54, 54));
        logoutButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Log Out");
        logoutButton.setBorder(null);
        logoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutButton.setFocusable(false);
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutButtonMouseExited(evt);
            }
        });
        logoutButton.addActionListener(this::logoutButtonActionPerformed);

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(logoHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(logoHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        mainCardPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainCardPanel.setLayout(new java.awt.CardLayout());

        payOrderPanel.setBackground(new java.awt.Color(235, 235, 235));

        orderNumTextField.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        orderNumTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 93, 93), 4));

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel1.setText("Enter Order Number:");

        orderNumButton.setBackground(new java.awt.Color(243, 93, 93));
        orderNumButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        orderNumButton.setForeground(new java.awt.Color(255, 255, 255));
        orderNumButton.setText("Enter");
        orderNumButton.setBorder(null);
        orderNumButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        orderNumButton.setFocusPainted(false);

        calculateButton.setBackground(new java.awt.Color(122, 255, 89));
        calculateButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        calculateButton.setForeground(new java.awt.Color(51, 51, 51));
        calculateButton.setText("Calculate");
        calculateButton.setAutoscrolls(true);
        calculateButton.setBorder(null);
        calculateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calculateButton.setFocusable(false);
        calculateButton.addActionListener(this::calculateButtonActionPerformed);

        paymentTextField.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        paymentTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 93, 93), 4));

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel3.setText("Enter Payment Amount:");

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Item", "Drinks", "Add-ons", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderTable.setShowGrid(false);
        jScrollPane2.setViewportView(orderTable);
        if (orderTable.getColumnModel().getColumnCount() > 0) {
            orderTable.getColumnModel().getColumn(0).setResizable(false);
            orderTable.getColumnModel().getColumn(1).setResizable(false);
            orderTable.getColumnModel().getColumn(2).setResizable(false);
            orderTable.getColumnModel().getColumn(3).setResizable(false);
            orderTable.getColumnModel().getColumn(4).setResizable(false);
        }

        addOrderButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        addOrderButton.setForeground(new java.awt.Color(243, 93, 93));
        addOrderButton.setText("Add");
        addOrderButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 102), 3));
        addOrderButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addOrderButton.setRequestFocusEnabled(false);

        editOrderButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        editOrderButton.setForeground(new java.awt.Color(243, 93, 93));
        editOrderButton.setText("Edit");
        editOrderButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 3));
        editOrderButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        deleteButtonOrder.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        deleteButtonOrder.setForeground(new java.awt.Color(243, 93, 93));
        deleteButtonOrder.setText("Delete");
        deleteButtonOrder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102), 3));
        deleteButtonOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel4.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(243, 93, 93));
        jLabel4.setText("Total Price: ");

        discountComboBox.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        discountComboBox.setForeground(new java.awt.Color(243, 93, 93));
        discountComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Senior Discount", "PWD" }));
        discountComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 93, 93), 3));

        jLabel5.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(243, 93, 93));
        jLabel5.setText("Select Discount:");

        totalPriceLabel.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        totalPriceLabel.setForeground(new java.awt.Color(243, 93, 93));
        totalPriceLabel.setText(" ");

        javax.swing.GroupLayout payOrderPanelLayout = new javax.swing.GroupLayout(payOrderPanel);
        payOrderPanel.setLayout(payOrderPanelLayout);
        payOrderPanelLayout.setHorizontalGroup(
            payOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payOrderPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(payOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(payOrderPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalPriceLabel))
                    .addGroup(payOrderPanelLayout.createSequentialGroup()
                        .addGroup(payOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(payOrderPanelLayout.createSequentialGroup()
                                .addComponent(orderNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(orderNumButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addGap(23, 23, 23)
                        .addGroup(payOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(payOrderPanelLayout.createSequentialGroup()
                                .addComponent(paymentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, payOrderPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(payOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addOrderButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editOrderButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, payOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(deleteButtonOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(discountComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 126, Short.MAX_VALUE))
        );
        payOrderPanelLayout.setVerticalGroup(
            payOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payOrderPanelLayout.createSequentialGroup()
                .addGroup(payOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(payOrderPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)
                        .addGroup(payOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(orderNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(orderNumButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(payOrderPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel3)
                        .addGap(7, 7, 7)
                        .addGroup(payOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(paymentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(payOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(payOrderPanelLayout.createSequentialGroup()
                        .addComponent(addOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(editOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(deleteButtonOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(discountComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(payOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(totalPriceLabel))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        mainCardPanel.add(payOrderPanel, "payOrderCard");

        createOrderPanel.setBackground(new java.awt.Color(235, 235, 235));

        jPanel5.setBackground(new java.awt.Color(235, 235, 235));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        createWNButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        createWNButton.setForeground(new java.awt.Color(243, 93, 93));
        createWNButton.setText("What's New");
        createWNButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 93, 93), 3));
        createWNButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(9, 14, 0, 6);
        jPanel5.add(createWNButton, gridBagConstraints);

        createCButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        createCButton.setForeground(new java.awt.Color(243, 93, 93));
        createCButton.setText("Chicken");
        createCButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 93, 93), 3));
        createCButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createCButton.addActionListener(this::createCButtonActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(9, 1, 0, 12);
        jPanel5.add(createCButton, gridBagConstraints);

        createPButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        createPButton.setForeground(new java.awt.Color(243, 93, 93));
        createPButton.setText("Pasta");
        createPButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 93, 93), 3));
        createPButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 47;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(9, 1, 0, 12);
        jPanel5.add(createPButton, gridBagConstraints);

        creatBButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        creatBButton.setForeground(new java.awt.Color(243, 93, 93));
        creatBButton.setText("Burgers");
        creatBButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 93, 93), 3));
        creatBButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(9, 1, 0, 12);
        jPanel5.add(creatBButton, gridBagConstraints);

        createDesButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        createDesButton.setForeground(new java.awt.Color(243, 93, 93));
        createDesButton.setText("Dessert");
        createDesButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 93, 93), 3));
        createDesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(9, 1, 0, 12);
        jPanel5.add(createDesButton, gridBagConstraints);

        createDrinkButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        createDrinkButton.setForeground(new java.awt.Color(243, 93, 93));
        createDrinkButton.setText("Drinks");
        createDrinkButton.setActionCommand("Drinks");
        createDrinkButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 93, 93), 3));
        createDrinkButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(9, 6, 9, 0);
        jPanel5.add(createDrinkButton, gridBagConstraints);

        creatAOButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        creatAOButton.setForeground(new java.awt.Color(243, 93, 93));
        creatAOButton.setText("Add-ons");
        creatAOButton.setToolTipText("");
        creatAOButton.setActionCommand("Add-ons");
        creatAOButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 93, 93), 3));
        creatAOButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(9, 0, 9, 12);
        jPanel5.add(creatAOButton, gridBagConstraints);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Item", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
        }

        decreaseQuanButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        decreaseQuanButton.setForeground(new java.awt.Color(243, 93, 93));
        decreaseQuanButton.setText("Decrease");
        decreaseQuanButton.setToolTipText("");
        decreaseQuanButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 93, 93), 3));
        decreaseQuanButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        increaseQuanButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        increaseQuanButton.setForeground(new java.awt.Color(243, 93, 93));
        increaseQuanButton.setText("Increase");
        increaseQuanButton.setToolTipText("");
        increaseQuanButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 93, 93), 3));
        increaseQuanButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        increaseQuanButton.addActionListener(this::increaseQuanButtonActionPerformed);

        removeButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        removeButton.setForeground(new java.awt.Color(243, 93, 93));
        removeButton.setText("Remove");
        removeButton.setToolTipText("");
        removeButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 93, 93), 3));
        removeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeButton.addActionListener(this::removeButtonActionPerformed);

        clearButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        clearButton.setForeground(new java.awt.Color(243, 93, 93));
        clearButton.setText("Cancel/Clear");
        clearButton.setToolTipText("");
        clearButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 93, 93), 3));
        clearButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        confirmOrderButtonCO.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        confirmOrderButtonCO.setForeground(new java.awt.Color(243, 93, 93));
        confirmOrderButtonCO.setText("Confirm Order");
        confirmOrderButtonCO.setToolTipText("");
        confirmOrderButtonCO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 102), 3));
        confirmOrderButtonCO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(243, 93, 93));
        jLabel2.setText("Total Amount:");

        totalAmountLabel.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        totalAmountLabel.setForeground(new java.awt.Color(243, 93, 93));
        totalAmountLabel.setText(" ");

        discountCOComboBox.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        discountCOComboBox.setForeground(new java.awt.Color(243, 93, 93));
        discountCOComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Senior Citizen", "PWD" }));
        discountCOComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 93, 93), 3));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout createOrderPanelLayout = new javax.swing.GroupLayout(createOrderPanel);
        createOrderPanel.setLayout(createOrderPanelLayout);
        createOrderPanelLayout.setHorizontalGroup(
            createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createOrderPanelLayout.createSequentialGroup()
                .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createOrderPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(createOrderPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(createOrderPanelLayout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(totalAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createOrderPanelLayout.createSequentialGroup()
                            .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(createOrderPanelLayout.createSequentialGroup()
                                    .addComponent(decreaseQuanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(increaseQuanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(createOrderPanelLayout.createSequentialGroup()
                                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(discountCOComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGap(1, 1, 1)))
                    .addComponent(confirmOrderButtonCO, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        createOrderPanelLayout.setVerticalGroup(
            createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createOrderPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(createOrderPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(totalAmountLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(decreaseQuanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(increaseQuanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(discountCOComboBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(confirmOrderButtonCO, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(createOrderPanelLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        mainCardPanel.add(createOrderPanel, "createOrderCard");

        editMenuPanel.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout editMenuPanelLayout = new javax.swing.GroupLayout(editMenuPanel);
        editMenuPanel.setLayout(editMenuPanelLayout);
        editMenuPanelLayout.setHorizontalGroup(
            editMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1064, Short.MAX_VALUE)
        );
        editMenuPanelLayout.setVerticalGroup(
            editMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
        );

        mainCardPanel.add(editMenuPanel, "editMenuCard");

        orderLogsPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout orderLogsPanelLayout = new javax.swing.GroupLayout(orderLogsPanel);
        orderLogsPanel.setLayout(orderLogsPanelLayout);
        orderLogsPanelLayout.setHorizontalGroup(
            orderLogsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1064, Short.MAX_VALUE)
        );
        orderLogsPanelLayout.setVerticalGroup(
            orderLogsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
        );

        mainCardPanel.add(orderLogsPanel, "orderLogsCard");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(mainCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setupRolePermissions() {
        if ("admin".equalsIgnoreCase(userRole)) {
            editMenuButton.setEnabled(true);
            orderLogsButton.setEnabled(true);
            payOrderButton.setEnabled(true);
            createOrderButton.setEnabled(true);
        } else if ("cashier".equalsIgnoreCase(userRole)) {
            editMenuButton.setEnabled(false);
            orderLogsButton.setEnabled(false);
            payOrderButton.setEnabled(true);
            createOrderButton.setEnabled(true);
            
            orderLogsButton.setBackground(new Color(173, 68, 68));
            editMenuButton.setBackground(new Color(173, 68, 68));
        }
    }
    
    private void payOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payOrderButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainCardPanel.getLayout();
        card.show(mainCardPanel, "payOrderCard");
        payOrderButton.setBackground(new Color(150, 47, 47));
    }//GEN-LAST:event_payOrderButtonActionPerformed

    private void payOrderButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payOrderButtonMouseExited
        // TODO add your handling code here:
        payOrderButton.setBackground(new Color(174,54,54));
    }//GEN-LAST:event_payOrderButtonMouseExited

    private void payOrderButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payOrderButtonMouseEntered
        // TODO add your handling code here:
        payOrderButton.setBackground(new Color(150, 47, 47));
    }//GEN-LAST:event_payOrderButtonMouseEntered

    private void createOrderButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createOrderButtonMouseEntered
        // TODO add your handling code here:
        createOrderButton.setBackground(new Color(150, 47, 47));
    }//GEN-LAST:event_createOrderButtonMouseEntered

    private void createOrderButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createOrderButtonMouseExited
        // TODO add your handling code here:
        createOrderButton.setBackground(new Color(174,54,54));
    }//GEN-LAST:event_createOrderButtonMouseExited

    private void orderLogsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderLogsButtonMouseEntered
        // TODO add your handling code here:
        if (orderLogsButton.isEnabled()) {
            orderLogsButton.setBackground(new Color(150, 47, 47));
        }
    }//GEN-LAST:event_orderLogsButtonMouseEntered

    private void orderLogsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderLogsButtonMouseExited
        // TODO add your handling code here:
        if (orderLogsButton.isEnabled()) {
        orderLogsButton.setBackground(new Color(174,54,54));
        }
    }//GEN-LAST:event_orderLogsButtonMouseExited

    private void editMenuButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMenuButtonMouseEntered
        // TODO add your handling code here:
        if(editMenuButton.isEnabled()){
        editMenuButton.setBackground(new Color(150, 47, 47));
        }
    }//GEN-LAST:event_editMenuButtonMouseEntered

    private void editMenuButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMenuButtonMouseExited
        // TODO add your handling code here:
        if(editMenuButton.isEnabled()){
        editMenuButton.setBackground(new Color(174,54,54));
        }
    }//GEN-LAST:event_editMenuButtonMouseExited

    private void logoutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseEntered
        // TODO add your handling code here:
        logoutButton.setBackground(new Color(150, 47, 47));
    }//GEN-LAST:event_logoutButtonMouseEntered

    private void logoutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseExited
        // TODO add your handling code here:
        logoutButton.setBackground(new Color(174,54,54));
    }//GEN-LAST:event_logoutButtonMouseExited

    private void orderLogsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderLogsButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainCardPanel.getLayout();
        card.show(mainCardPanel, "orderLogsCard");
    }//GEN-LAST:event_orderLogsButtonActionPerformed

    private void createOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createOrderButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainCardPanel.getLayout();
        card.show(mainCardPanel, "createOrderCard");
    }//GEN-LAST:event_createOrderButtonActionPerformed

    private void editMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMenuButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainCardPanel.getLayout();
        card.show(mainCardPanel, "editMenuCard");
    }//GEN-LAST:event_editMenuButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        calculateChange();
    }//GEN-LAST:event_calculateButtonActionPerformed

    private void createCButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createCButtonActionPerformed

    private void increaseQuanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_increaseQuanButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_increaseQuanButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeButtonActionPerformed

    // ---- Pay Order panel logic ----

    /** Returns 0.20 for Senior Discount / PWD, otherwise 0. */
    private double getDiscountRate() {
        String discount = (String) discountComboBox.getSelectedItem();
        return ("Senior Discount".equals(discount) || "PWD".equals(discount)) ? 0.20 : 0.0;
    }

    private void loadOrder() {
        String orderNumStr = orderNumTextField.getText().trim();
        if (orderNumStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter an order number.");
            return;
        }
        int orderNum;
        try {
            orderNum = Integer.parseInt(orderNumStr);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Order number must be a whole number.");
            return;
        }

        String sql = "SELECT orderId, total, discountRate, finalTotal, orderStatus FROM orders WHERE orderNumber = ?";
        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setInt(1, orderNum);
            try (ResultSet rs = ps.executeQuery()) {
                if (!rs.next()) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Order #" + orderNum + " not found.");
                    return;
                }
                currentOrderId   = rs.getInt("orderId");
                currentTotal     = rs.getDouble("total");
                String status    = rs.getString("orderStatus");
                currentOrderPaid = "paid".equalsIgnoreCase(status);

                if (currentOrderPaid) {
                    javax.swing.JOptionPane.showMessageDialog(this,
                        "Order #" + orderNum + " has already been paid.");
                    return;
                }
            }
        } catch (SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage());
            return;
        }

        loadOrderItems();
        applyDiscount();
    }

    private void loadOrderItems() {
        String sql =
            "SELECT oi.orderItemId, mi.itemName, d.drinkName, " +
            "GROUP_CONCAT(a.addonName ORDER BY a.addonId SEPARATOR ', ') AS addons, " +
            "oi.quantity, oi.itemTotal " +
            "FROM order_items oi " +
            "JOIN menu_items mi ON mi.itemID = oi.menuItemId " +
            "LEFT JOIN order_item_drinks oid ON oid.orderItemId = oi.orderItemId " +
            "LEFT JOIN drinks d ON d.drinkID = oid.drinkId " +
            "LEFT JOIN order_item_addons oia ON oia.orderItemId = oi.orderItemId " +
            "LEFT JOIN add_ons a ON a.addonId = oia.addonId " +
            "WHERE oi.orderId = ? " +
            "GROUP BY oi.orderItemId, mi.itemName, d.drinkName, oi.quantity, oi.itemTotal";

        DefaultTableModel model = (DefaultTableModel) orderTable.getModel();
        model.setRowCount(0);
        orderItemIds.clear();

        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setInt(1, currentOrderId);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    orderItemIds.add(rs.getInt("orderItemId"));
                    String drinks = rs.getString("drinkName");
                    String addons = rs.getString("addons");
                    model.addRow(new Object[]{
                        rs.getString("itemName"),
                        drinks != null ? drinks : "None",
                        addons != null ? addons : "None",
                        rs.getInt("quantity"),
                        rs.getDouble("itemTotal")
                    });
                }
            }
        } catch (SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error loading order items: " + ex.getMessage());
        }
    }

    private void applyDiscount() {
        double discountRate   = getDiscountRate();
        double discountAmount = currentTotal * discountRate;
        currentFinalTotal     = currentTotal - discountAmount;
        totalPriceLabel.setText(String.format("\u20b1%.2f", currentFinalTotal));
    }

    private void calculateChange() {
        if (currentOrderId == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please load an order first.");
            return;
        }
        String paymentStr = paymentTextField.getText().trim();
        if (paymentStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a payment amount.");
            return;
        }
        double payment;
        try {
            payment = Double.parseDouble(paymentStr);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid payment amount.");
            return;
        }
        if (payment < currentFinalTotal) {
            javax.swing.JOptionPane.showMessageDialog(this,
                String.format("Payment is insufficient.\nTotal due: \u20b1%.2f", currentFinalTotal));
            return;
        }
        double change = payment - currentFinalTotal;
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
            String.format("Total:    \u20b1%.2f%nPayment:  \u20b1%.2f%nChange:   \u20b1%.2f%n%nConfirm payment?",
                currentFinalTotal, payment, change),
            "Confirm Payment", javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            processPayment(payment, change);
        }
    }

    private void processPayment(double payment, double change) {
        double discountRate   = getDiscountRate();
        double discountAmount = currentTotal * discountRate;
        try {
            conn.setAutoCommit(false);

            String updateOrder = "UPDATE orders SET discountRate=?, discountAmount=?, finalTotal=?, orderStatus='paid' WHERE orderId=?";
            try (PreparedStatement ps = conn.prepareStatement(updateOrder)) {
                ps.setDouble(1, discountRate);
                ps.setDouble(2, discountAmount);
                ps.setDouble(3, currentFinalTotal);
                ps.setInt(4, currentOrderId);
                ps.executeUpdate();
            }

            String upsertPayment =
                "INSERT INTO payments(orderId, amountReceived, changeAmount) VALUES(?,?,?) " +
                "ON DUPLICATE KEY UPDATE amountReceived=VALUES(amountReceived), changeAmount=VALUES(changeAmount)";
            try (PreparedStatement ps = conn.prepareStatement(upsertPayment)) {
                ps.setInt(1, currentOrderId);
                ps.setDouble(2, payment);
                ps.setDouble(3, change);
                ps.executeUpdate();
            }

            conn.commit();
            javax.swing.JOptionPane.showMessageDialog(this,
                String.format("Payment processed!\nChange: \u20b1%.2f", change));
            clearPayOrderForm();
        } catch (SQLException ex) {
            try { conn.rollback(); } catch (SQLException rollbackEx) {
                logger.log(java.util.logging.Level.SEVERE, "Rollback failed", rollbackEx);
            }
            javax.swing.JOptionPane.showMessageDialog(this, "Error processing payment: " + ex.getMessage());
        } finally {
            try { conn.setAutoCommit(true); } catch (SQLException autoCommitEx) {
                logger.log(java.util.logging.Level.SEVERE, "Failed to restore auto-commit", autoCommitEx);
            }
        }
    }

    private void addOrderItem() {
        if (currentOrderId == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please load an order first.");
            return;
        }

        List<String> names  = new ArrayList<>();
        List<Integer> ids   = new ArrayList<>();
        List<Double> prices = new ArrayList<>();

        try (PreparedStatement ps = conn.prepareStatement(
                "SELECT itemID, itemName, price FROM menu_items ORDER BY itemName");
             ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                ids.add(rs.getInt("itemID"));
                names.add(rs.getString("itemName"));
                prices.add(rs.getDouble("price"));
            }
        } catch (SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error loading menu: " + ex.getMessage());
            return;
        }

        if (names.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "No menu items available.");
            return;
        }

        javax.swing.JComboBox<String> itemCombo = new javax.swing.JComboBox<>(names.toArray(new String[0]));
        javax.swing.JTextField qtyField = new javax.swing.JTextField("1", 6);
        Object[] message = {"Select Menu Item:", itemCombo, "Quantity:", qtyField};

        int result = javax.swing.JOptionPane.showConfirmDialog(this, message,
            "Add Item to Order", javax.swing.JOptionPane.OK_CANCEL_OPTION);
        if (result != javax.swing.JOptionPane.OK_OPTION) return;

        int selectedIdx = itemCombo.getSelectedIndex();
        int menuItemId  = ids.get(selectedIdx);
        double price    = prices.get(selectedIdx);
        int qty;
        try {
            qty = Integer.parseInt(qtyField.getText().trim());
            if (qty <= 0) throw new NumberFormatException();
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid quantity (positive integer).");
            return;
        }
        double itemTotal = price * qty;

        try {
            conn.setAutoCommit(false);

            try (PreparedStatement ps = conn.prepareStatement(
                    "INSERT INTO order_items(orderId, menuItemId, quantity, pricePerItem, itemTotal) VALUES(?,?,?,?,?)")) {
                ps.setInt(1, currentOrderId);
                ps.setInt(2, menuItemId);
                ps.setInt(3, qty);
                ps.setDouble(4, price);
                ps.setDouble(5, itemTotal);
                ps.executeUpdate();
            }

            currentTotal = recalcOrderTotal();
            conn.commit();

            loadOrderItems();
            applyDiscount();
        } catch (SQLException ex) {
            try { conn.rollback(); } catch (SQLException rollbackEx) {
                logger.log(java.util.logging.Level.SEVERE, "Rollback failed", rollbackEx);
            }
            javax.swing.JOptionPane.showMessageDialog(this, "Error adding item: " + ex.getMessage());
        } finally {
            try { conn.setAutoCommit(true); } catch (SQLException autoCommitEx) {
                logger.log(java.util.logging.Level.SEVERE, "Failed to restore auto-commit", autoCommitEx);
            }
        }
    }

    private void editOrderItem() {
        int selectedRow = orderTable.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select an item to edit.");
            return;
        }

        int orderItemId  = orderItemIds.get(selectedRow);
        int currentQty   = (Integer) orderTable.getValueAt(selectedRow, 3);
        double rowTotal  = (Double) orderTable.getValueAt(selectedRow, 4);
        double unitPrice = (currentQty > 0) ? rowTotal / currentQty : rowTotal;

        String input = javax.swing.JOptionPane.showInputDialog(this,
            "Enter new quantity:", String.valueOf(currentQty));
        if (input == null || input.trim().isEmpty()) return;

        int newQty;
        try {
            newQty = Integer.parseInt(input.trim());
            if (newQty <= 0) throw new NumberFormatException();
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid quantity (positive integer).");
            return;
        }

        double newItemTotal = unitPrice * newQty;

        try {
            conn.setAutoCommit(false);

            try (PreparedStatement ps = conn.prepareStatement(
                    "UPDATE order_items SET quantity=?, itemTotal=? WHERE orderItemId=?")) {
                ps.setInt(1, newQty);
                ps.setDouble(2, newItemTotal);
                ps.setInt(3, orderItemId);
                ps.executeUpdate();
            }

            currentTotal = recalcOrderTotal();
            conn.commit();

            loadOrderItems();
            applyDiscount();
        } catch (SQLException ex) {
            try { conn.rollback(); } catch (SQLException rollbackEx) {
                logger.log(java.util.logging.Level.SEVERE, "Rollback failed", rollbackEx);
            }
            javax.swing.JOptionPane.showMessageDialog(this, "Error editing item: " + ex.getMessage());
        } finally {
            try { conn.setAutoCommit(true); } catch (SQLException autoCommitEx) {
                logger.log(java.util.logging.Level.SEVERE, "Failed to restore auto-commit", autoCommitEx);
            }
        }
    }

    private void deleteOrderItem() {
        int selectedRow = orderTable.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select an item to delete.");
            return;
        }

        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
            "Are you sure you want to delete this item?",
            "Confirm Delete", javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm != javax.swing.JOptionPane.YES_OPTION) return;

        int orderItemId = orderItemIds.get(selectedRow);

        try {
            conn.setAutoCommit(false);

            try (PreparedStatement ps = conn.prepareStatement(
                    "DELETE FROM order_item_addons WHERE orderItemId=?")) {
                ps.setInt(1, orderItemId);
                ps.executeUpdate();
            }
            try (PreparedStatement ps = conn.prepareStatement(
                    "DELETE FROM order_item_drinks WHERE orderItemId=?")) {
                ps.setInt(1, orderItemId);
                ps.executeUpdate();
            }
            try (PreparedStatement ps = conn.prepareStatement(
                    "DELETE FROM order_items WHERE orderItemId=?")) {
                ps.setInt(1, orderItemId);
                ps.executeUpdate();
            }

            currentTotal = recalcOrderTotal();
            conn.commit();

            loadOrderItems();
            applyDiscount();
        } catch (SQLException ex) {
            try { conn.rollback(); } catch (SQLException rollbackEx) {
                logger.log(java.util.logging.Level.SEVERE, "Rollback failed", rollbackEx);
            }
            javax.swing.JOptionPane.showMessageDialog(this, "Error deleting item: " + ex.getMessage());
        } finally {
            try { conn.setAutoCommit(true); } catch (SQLException autoCommitEx) {
                logger.log(java.util.logging.Level.SEVERE, "Failed to restore auto-commit", autoCommitEx);
            }
        }
    }

    /**
     * Recalculates and persists only the {@code total} column in the orders table.
     * {@code finalTotal} (discount-adjusted) is set separately by {@link #processPayment}.
     */
    private double recalcOrderTotal() throws SQLException {
        double newTotal = 0;
        try (PreparedStatement ps = conn.prepareStatement(
                "SELECT COALESCE(SUM(itemTotal), 0) AS total FROM order_items WHERE orderId=?")) {
            ps.setInt(1, currentOrderId);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) newTotal = rs.getDouble("total");
            }
        }
        try (PreparedStatement ps = conn.prepareStatement(
                "UPDATE orders SET total=? WHERE orderId=?")) {
            ps.setDouble(1, newTotal);
            ps.setInt(2, currentOrderId);
            ps.executeUpdate();
        }
        return newTotal;
    }

    private void clearPayOrderForm() {
        currentOrderId    = 0;
        currentTotal      = 0;
        currentFinalTotal = 0;
        currentOrderPaid  = false;
        orderItemIds.clear();
        orderNumTextField.setText("");
        paymentTextField.setText("");
        totalPriceLabel.setText(" ");
        discountComboBox.setSelectedIndex(0);
        ((DefaultTableModel) orderTable.getModel()).setRowCount(0);
    }

    // ---- end Pay Order panel logic ----

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        String userRole = "admin";
        java.awt.EventQueue.invokeLater(() -> new AdminMain(userRole).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addOrderButton;
    private javax.swing.JButton calculateButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton confirmOrderButtonCO;
    private javax.swing.JButton creatAOButton;
    private javax.swing.JButton creatBButton;
    private javax.swing.JButton createCButton;
    private javax.swing.JButton createDesButton;
    private javax.swing.JButton createDrinkButton;
    private javax.swing.JButton createOrderButton;
    private javax.swing.JPanel createOrderPanel;
    private javax.swing.JButton createPButton;
    private javax.swing.JButton createWNButton;
    private javax.swing.JButton decreaseQuanButton;
    private javax.swing.JButton deleteButtonOrder;
    private javax.swing.JComboBox<String> discountCOComboBox;
    private javax.swing.JComboBox<String> discountComboBox;
    private javax.swing.JButton editMenuButton;
    private javax.swing.JPanel editMenuPanel;
    private javax.swing.JButton editOrderButton;
    private javax.swing.JButton increaseQuanButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel logoHolder;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel mainCardPanel;
    private javax.swing.JButton orderLogsButton;
    private javax.swing.JPanel orderLogsPanel;
    private javax.swing.JButton orderNumButton;
    private javax.swing.JTextField orderNumTextField;
    private javax.swing.JTable orderTable;
    private javax.swing.JButton payOrderButton;
    private javax.swing.JPanel payOrderPanel;
    private javax.swing.JTextField paymentTextField;
    private javax.swing.JButton removeButton;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JLabel totalAmountLabel;
    private javax.swing.JLabel totalPriceLabel;
    // End of variables declaration//GEN-END:variables
}
