/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;

/**
 *
 * @author jakob
 */
public class AdminMain extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminMain.class.getName());
    
    ImageIcon icon = new ImageIcon("images/KioskIcon.png");
    Image kioskIcon = icon.getImage();
    
    //SQL
    Connection conn;
    Statement stmt;
    PreparedStatement ps;
    ResultSet rs;
    
    ImageIcon image = new ImageIcon("Images/Logo.png");
    Image scaledImage = image.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH);
    ImageIcon resizedImage = new ImageIcon(scaledImage);
    
    private String userRole;

    public AdminMain(String userRole) {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setIconImage(kioskIcon);
        setTitle("Fast Food");
        conn = DatabaseConnection.connectDatabase(); //SQL Connection
        logoHolder.setIcon(resizedImage);
        
        this.userRole = userRole;
        setupRolePermissions();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        logoHolder = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        createOrderButton = new javax.swing.JButton();
        payOrderButton = new javax.swing.JButton();
        orderLogsButton = new javax.swing.JButton();
        editMenuButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        logoutButton = new javax.swing.JButton();
        mainCardPanel = new javax.swing.JPanel();
        payOrderPanel = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        createOrderPanel = new javax.swing.JPanel();
        editMenuPanel = new javax.swing.JPanel();
        orderLogsPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 214, 102));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setDoubleBuffered(false);

        sidePanel.setBackground(new java.awt.Color(243, 93, 93));

        logoHolder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jPanel3.setBackground(new java.awt.Color(243, 93, 93));

        createOrderButton.setBackground(new java.awt.Color(174, 54, 54));
        createOrderButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        createOrderButton.setForeground(new java.awt.Color(255, 255, 255));
        createOrderButton.setText("Create Order");
        createOrderButton.setBorder(null);
        createOrderButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createOrderButton.setFocusable(false);
        createOrderButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        createOrderButton.setMaximumSize(new java.awt.Dimension(36, 28));
        createOrderButton.setMinimumSize(new java.awt.Dimension(36, 28));
        createOrderButton.setPreferredSize(new java.awt.Dimension(36, 28));
        createOrderButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                createOrderButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                createOrderButtonMouseExited(evt);
            }
        });
        createOrderButton.addActionListener(this::createOrderButtonActionPerformed);

        payOrderButton.setBackground(new java.awt.Color(174, 54, 54));
        payOrderButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        payOrderButton.setForeground(new java.awt.Color(255, 255, 255));
        payOrderButton.setText("Pay Order");
        payOrderButton.setBorder(null);
        payOrderButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        payOrderButton.setFocusPainted(false);
        payOrderButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        payOrderButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                payOrderButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                payOrderButtonMouseExited(evt);
            }
        });
        payOrderButton.addActionListener(this::payOrderButtonActionPerformed);

        orderLogsButton.setBackground(new java.awt.Color(174, 54, 54));
        orderLogsButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        orderLogsButton.setForeground(new java.awt.Color(255, 255, 255));
        orderLogsButton.setText("Order Logs");
        orderLogsButton.setBorder(null);
        orderLogsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        orderLogsButton.setFocusable(false);
        orderLogsButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        orderLogsButton.setMaximumSize(new java.awt.Dimension(36, 28));
        orderLogsButton.setMinimumSize(new java.awt.Dimension(36, 28));
        orderLogsButton.setPreferredSize(new java.awt.Dimension(36, 28));
        orderLogsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                orderLogsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                orderLogsButtonMouseExited(evt);
            }
        });
        orderLogsButton.addActionListener(this::orderLogsButtonActionPerformed);

        editMenuButton.setBackground(new java.awt.Color(174, 54, 54));
        editMenuButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        editMenuButton.setForeground(new java.awt.Color(255, 255, 255));
        editMenuButton.setText("Edit Menu");
        editMenuButton.setBorder(null);
        editMenuButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editMenuButton.setFocusable(false);
        editMenuButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        editMenuButton.setMaximumSize(new java.awt.Dimension(36, 28));
        editMenuButton.setMinimumSize(new java.awt.Dimension(36, 28));
        editMenuButton.setPreferredSize(new java.awt.Dimension(36, 28));
        editMenuButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editMenuButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editMenuButtonMouseExited(evt);
            }
        });
        editMenuButton.addActionListener(this::editMenuButtonActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(orderLogsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(payOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(editMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(payOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderLogsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(153, 214, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 5));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        logoutButton.setBackground(new java.awt.Color(174, 54, 54));
        logoutButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Log Out");
        logoutButton.setBorder(null);
        logoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutButton.setFocusable(false);
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutButtonMouseExited(evt);
            }
        });
        logoutButton.addActionListener(this::logoutButtonActionPerformed);

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(logoHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(logoHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        mainCardPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainCardPanel.setLayout(new java.awt.CardLayout());

        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 93, 93), 4));

        javax.swing.GroupLayout payOrderPanelLayout = new javax.swing.GroupLayout(payOrderPanel);
        payOrderPanel.setLayout(payOrderPanelLayout);
        payOrderPanelLayout.setHorizontalGroup(
            payOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payOrderPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(655, Short.MAX_VALUE))
        );
        payOrderPanelLayout.setVerticalGroup(
            payOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payOrderPanelLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(563, Short.MAX_VALUE))
        );

        mainCardPanel.add(payOrderPanel, "payOrderCard");

        createOrderPanel.setBackground(new java.awt.Color(102, 255, 204));

        javax.swing.GroupLayout createOrderPanelLayout = new javax.swing.GroupLayout(createOrderPanel);
        createOrderPanel.setLayout(createOrderPanelLayout);
        createOrderPanelLayout.setHorizontalGroup(
            createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        createOrderPanelLayout.setVerticalGroup(
            createOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 764, Short.MAX_VALUE)
        );

        mainCardPanel.add(createOrderPanel, "createOrderCard");

        editMenuPanel.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout editMenuPanelLayout = new javax.swing.GroupLayout(editMenuPanel);
        editMenuPanel.setLayout(editMenuPanelLayout);
        editMenuPanelLayout.setHorizontalGroup(
            editMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        editMenuPanelLayout.setVerticalGroup(
            editMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 764, Short.MAX_VALUE)
        );

        mainCardPanel.add(editMenuPanel, "editMenuCard");

        orderLogsPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout orderLogsPanelLayout = new javax.swing.GroupLayout(orderLogsPanel);
        orderLogsPanel.setLayout(orderLogsPanelLayout);
        orderLogsPanelLayout.setHorizontalGroup(
            orderLogsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        orderLogsPanelLayout.setVerticalGroup(
            orderLogsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 764, Short.MAX_VALUE)
        );

        mainCardPanel.add(orderLogsPanel, "orderLogsCard");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(mainCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setupRolePermissions() {
        if ("admin".equalsIgnoreCase(userRole)) {
            editMenuButton.setEnabled(true);
            orderLogsButton.setEnabled(true);
            payOrderButton.setEnabled(true);
            createOrderButton.setEnabled(true);
        } else if ("cashier".equalsIgnoreCase(userRole)) {
            editMenuButton.setEnabled(false);
            orderLogsButton.setEnabled(false);
            payOrderButton.setEnabled(true);
            createOrderButton.setEnabled(true);
            
            orderLogsButton.setBackground(new Color(173, 68, 68));
            editMenuButton.setBackground(new Color(173, 68, 68));
        }
    }
    
    private void payOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payOrderButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainCardPanel.getLayout();
        card.show(mainCardPanel, "payOrderCard");
        payOrderButton.setBackground(new Color(150, 47, 47));
    }//GEN-LAST:event_payOrderButtonActionPerformed

    private void payOrderButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payOrderButtonMouseExited
        // TODO add your handling code here:
        payOrderButton.setBackground(new Color(174,54,54));
    }//GEN-LAST:event_payOrderButtonMouseExited

    private void payOrderButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payOrderButtonMouseEntered
        // TODO add your handling code here:
        payOrderButton.setBackground(new Color(150, 47, 47));
    }//GEN-LAST:event_payOrderButtonMouseEntered

    private void createOrderButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createOrderButtonMouseEntered
        // TODO add your handling code here:
        createOrderButton.setBackground(new Color(150, 47, 47));
    }//GEN-LAST:event_createOrderButtonMouseEntered

    private void createOrderButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createOrderButtonMouseExited
        // TODO add your handling code here:
        createOrderButton.setBackground(new Color(174,54,54));
    }//GEN-LAST:event_createOrderButtonMouseExited

    private void orderLogsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderLogsButtonMouseEntered
        // TODO add your handling code here:
        if (orderLogsButton.isEnabled()) {
            orderLogsButton.setBackground(new Color(150, 47, 47));
        }
    }//GEN-LAST:event_orderLogsButtonMouseEntered

    private void orderLogsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderLogsButtonMouseExited
        // TODO add your handling code here:
        if (orderLogsButton.isEnabled()) {
        orderLogsButton.setBackground(new Color(174,54,54));
        }
    }//GEN-LAST:event_orderLogsButtonMouseExited

    private void editMenuButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMenuButtonMouseEntered
        // TODO add your handling code here:
        if(editMenuButton.isEnabled()){
        editMenuButton.setBackground(new Color(150, 47, 47));
        }
    }//GEN-LAST:event_editMenuButtonMouseEntered

    private void editMenuButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMenuButtonMouseExited
        // TODO add your handling code here:
        if(editMenuButton.isEnabled()){
        editMenuButton.setBackground(new Color(174,54,54));
        }
    }//GEN-LAST:event_editMenuButtonMouseExited

    private void logoutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseEntered
        // TODO add your handling code here:
        logoutButton.setBackground(new Color(150, 47, 47));
    }//GEN-LAST:event_logoutButtonMouseEntered

    private void logoutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseExited
        // TODO add your handling code here:
        logoutButton.setBackground(new Color(174,54,54));
    }//GEN-LAST:event_logoutButtonMouseExited

    private void orderLogsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderLogsButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainCardPanel.getLayout();
        card.show(mainCardPanel, "orderLogsCard");
    }//GEN-LAST:event_orderLogsButtonActionPerformed

    private void createOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createOrderButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainCardPanel.getLayout();
        card.show(mainCardPanel, "createOrderCard");
    }//GEN-LAST:event_createOrderButtonActionPerformed

    private void editMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMenuButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainCardPanel.getLayout();
        card.show(mainCardPanel, "editMenuCard");
    }//GEN-LAST:event_editMenuButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        String userRole = "cashier";
        java.awt.EventQueue.invokeLater(() -> new AdminMain(userRole).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createOrderButton;
    private javax.swing.JPanel createOrderPanel;
    private javax.swing.JButton editMenuButton;
    private javax.swing.JPanel editMenuPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel logoHolder;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel mainCardPanel;
    private javax.swing.JButton orderLogsButton;
    private javax.swing.JPanel orderLogsPanel;
    private javax.swing.JButton payOrderButton;
    private javax.swing.JPanel payOrderPanel;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}
