package Kiosk;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author admin
 */
public class SelectOrder extends javax.swing.JFrame {

    private final String orderType;
    private Connection conn;
    private MenuSQL menuQuery;
    private Cart cart;

    public SelectOrder(String orderType, Cart cart) {
        this.orderType = orderType;
        this.cart = cart;
        initComponents();
        pics();

    }

    public SelectOrder(String orderType) {
        this(orderType, new Cart(orderType));
    }

    private void pics() {
        setLocationRelativeTo(null);

        conn = DatabaseConnection.connectDatabase();
        menuQuery = new MenuSQL(conn);

        steplbl2.setText(orderType);
        steplbl.setText(orderType);

        ImageSize.setFillImage(band, "Images/christmas.png");
        ImageSize.setFillImage(lbllogo2, "Images/Logo.png");

        loadWhatsNew();
        refreshOrderTotal();

    }

    private boolean hasConnection() {
        if (conn == null) {
            JOptionPane.showMessageDialog(this, "Database connection failed.");
            return false;
        }
        return true;
    }

    private void clearMenu() {
        panelMenu.removeAll();
        panelMenu.revalidate();
        panelMenu.repaint();
    }

    private void addMenuItem(MenuItemData item) {
        MenuPanel panel = new MenuPanel(
                item.getId(),
                item.getName(),
                item.getPrice(),
                item.getImagePath()
        );

        panel.setCardClick(new Runnable() {
            @Override
            public void run() {
                openCustomizeFrame(item, -1);
            }
        });

        panelMenu.add(panel);
    }

    private void openCustomizeFrame(MenuItemData item, int editIndex) {
        Customize customize = new Customize(conn, item, cart, editIndex);
        customize.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                refreshOrderTotal();
                SelectOrder.this.toFront();
                SelectOrder.this.requestFocus();
            }
        });
        customize.setVisible(true);
    }

    private void refreshOrderTotal() {
        lblCategory3.setText(String.format("%.2f", cart.getTotal()));
    }

    private void displayItems(String title, List<MenuItemData> items) {
        clearMenu();
        lblCategory.setText(title);

        for (MenuItemData item : items) {
            addMenuItem(item);
        }

        panelMenu.revalidate();
        panelMenu.repaint();
    }

    private void showLoadError(String title, SQLException e) {
        JOptionPane.showMessageDialog(this, "Error loading " + title + ": " + e.getMessage());
    }

    private void loadWhatsNew() {
        loadCategory(1001, "What's New");
    }

    private void loadChicken() {
        loadCategory(1002, "Chicken");
    }

    private void loadPasta() {
        loadCategory(1003, "Pasta");
    }

    private void loadBurgers() {
        loadCategory(1004, "Burgers");
    }

    private void loadDesserts() {
        loadCategory(1005, "Desserts");
    }

    private void loadCategory(int categoryId, String categoryTitle) {
        if (!hasConnection()) {
            return;
        }

        try {
            displayItems(categoryTitle, menuQuery.findByCategoryId(categoryId));
        } catch (SQLException e) {
            showLoadError(categoryTitle, e);
        }
    }

    private void loadDrinks() {
        if (!hasConnection()) {
            return;
        }

        try {
            displayItems("Drinks", menuQuery.findDrinks());
        } catch (SQLException e) {
            showLoadError("Drinks", e);
        }
    }

    private void loadAddons() {
        if (!hasConnection()) {
            return;
        }

        try {
            displayItems("Add Ons", menuQuery.findAddons());
        } catch (SQLException e) {
            showLoadError("Add Ons", e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        steplbl = new javax.swing.JLabel();
        panelCategories = new javax.swing.JPanel();
        btnwhatsnew = new javax.swing.JButton();
        btnchicken = new javax.swing.JButton();
        btnpasta = new javax.swing.JButton();
        btnburger = new javax.swing.JButton();
        btndrink = new javax.swing.JButton();
        btndessert = new javax.swing.JButton();
        btnaddons = new javax.swing.JButton();
        lbllogo2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblCategory1 = new javax.swing.JLabel();
        lblCategory2 = new javax.swing.JLabel();
        lblCategory3 = new javax.swing.JLabel();
        btnViewOrder = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        band = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblCategory = new javax.swing.JLabel();
        panelScroll = new javax.swing.JScrollPane();
        panelMenu = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        steplbl2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(171, 48, 61));
        jPanel3.setPreferredSize(new java.awt.Dimension(105, 50));
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Step 1");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(30, 10, 89, 16);

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Step 2");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(140, 10, 89, 16);

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Select Order");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(140, 20, 89, 20);

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Step 2");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(270, 10, 89, 16);

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Payment");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(270, 20, 89, 20);

        jLabel8.setFont(new java.awt.Font("Arial Narrow", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Step 3");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(390, 10, 89, 16);

        jLabel9.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Checkout");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(390, 20, 89, 20);

        jPanel7.setBackground(new java.awt.Color(255, 204, 18));
        jPanel7.setPreferredSize(new java.awt.Dimension(100, 3));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel7);
        jPanel7.setBounds(128, 45, 100, 4);

        steplbl.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        steplbl.setForeground(new java.awt.Color(255, 255, 255));
        steplbl.setText("Dine In");
        jPanel3.add(steplbl);
        steplbl.setBounds(30, 20, 89, 20);

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        panelCategories.setBackground(new java.awt.Color(255, 255, 255));
        panelCategories.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnwhatsnew.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        btnwhatsnew.setForeground(new java.awt.Color(171, 48, 61));
        btnwhatsnew.setText("What's New");
        btnwhatsnew.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(171, 48, 61), 2));
        btnwhatsnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnwhatsnewActionPerformed(evt);
            }
        });
        panelCategories.add(btnwhatsnew, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 102, 50));

        btnchicken.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        btnchicken.setForeground(new java.awt.Color(171, 48, 61));
        btnchicken.setText("Chicken");
        btnchicken.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(171, 48, 61), 2));
        btnchicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchickenActionPerformed(evt);
            }
        });
        panelCategories.add(btnchicken, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 102, 50));

        btnpasta.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        btnpasta.setForeground(new java.awt.Color(171, 48, 61));
        btnpasta.setText("Pasta");
        btnpasta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(171, 48, 61), 2));
        btnpasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpastaActionPerformed(evt);
            }
        });
        panelCategories.add(btnpasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 102, 50));

        btnburger.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        btnburger.setForeground(new java.awt.Color(171, 48, 61));
        btnburger.setText("Burger");
        btnburger.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(171, 48, 61), 2));
        btnburger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnburgerActionPerformed(evt);
            }
        });
        panelCategories.add(btnburger, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 102, 50));

        btndrink.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        btndrink.setForeground(new java.awt.Color(171, 48, 61));
        btndrink.setText("Drink");
        btndrink.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(171, 48, 61), 2));
        btndrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndrinkActionPerformed(evt);
            }
        });
        panelCategories.add(btndrink, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 102, 50));

        btndessert.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        btndessert.setForeground(new java.awt.Color(171, 48, 61));
        btndessert.setText("Dessert");
        btndessert.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(171, 48, 61), 2));
        btndessert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndessertActionPerformed(evt);
            }
        });
        panelCategories.add(btndessert, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 102, 50));

        btnaddons.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        btnaddons.setForeground(new java.awt.Color(171, 48, 61));
        btnaddons.setText("Add ons");
        btnaddons.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(171, 48, 61), 2));
        btnaddons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddonsActionPerformed(evt);
            }
        });
        panelCategories.add(btnaddons, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 102, 50));
        panelCategories.add(lbllogo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 2, 102, 90));

        jPanel2.add(panelCategories, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 97, -1, 540));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        lblCategory1.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        lblCategory1.setText("Item Total");

        lblCategory2.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        lblCategory2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCategory2.setText("Total");

        lblCategory3.setFont(new java.awt.Font("Arial Narrow", 1, 22)); // NOI18N
        lblCategory3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCategory3.setText("00.00");

        btnViewOrder.setBackground(new java.awt.Color(171, 48, 61));
        btnViewOrder.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        btnViewOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnViewOrder.setText("VIEW ORDER");
        btnViewOrder.setBorder(null);
        btnViewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewOrderActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(171, 48, 61));
        jButton1.setText("CANCEL");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(171, 48, 61), 2));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblCategory1)
                        .addGap(282, 282, 282)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(lblCategory2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCategory3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(btnViewOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCategory2)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblCategory3))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCategory1)))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 678, 494, -1));
        jPanel2.add(band, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 56, 500, 35));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        lblCategory.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        lblCategory.setForeground(new java.awt.Color(171, 48, 61));
        lblCategory.setText("What's New");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 97, 365, -1));

        panelScroll.setBackground(new java.awt.Color(255, 255, 255));
        panelScroll.setBorder(null);
        panelScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        panelScroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        panelScroll.setViewportView(panelMenu);

        panelMenu.setBackground(new java.awt.Color(255, 255, 255));
        panelMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelMenu.setMaximumSize(new java.awt.Dimension(363, 486));
        panelMenu.setMinimumSize(new java.awt.Dimension(363, 486));
        panelMenu.setLayout(new java.awt.GridLayout(0, 2, 10, 10));
        panelScroll.setViewportView(panelMenu);

        jPanel2.add(panelScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 335, 367));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 844, 500, -1));

        jPanel8.setBackground(new java.awt.Color(255, 204, 18));

        steplbl2.setFont(new java.awt.Font("Arial Narrow", 1, 20)); // NOI18N
        steplbl2.setForeground(new java.awt.Color(255, 255, 255));
        steplbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        steplbl2.setText("Dine In");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(steplbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(steplbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 639, 500, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 800));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddonsActionPerformed
        loadAddons();
    }//GEN-LAST:event_btnaddonsActionPerformed

    private void btndessertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndessertActionPerformed
        // TODO add your handling code here:
        loadDesserts();
    }//GEN-LAST:event_btndessertActionPerformed

    private void btndrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndrinkActionPerformed
        // TODO add your handling code here:
        loadDrinks();
    }//GEN-LAST:event_btndrinkActionPerformed

    private void btnburgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnburgerActionPerformed
        // TODO add your handling code here:
        loadBurgers();
    }//GEN-LAST:event_btnburgerActionPerformed

    private void btnpastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpastaActionPerformed
        // TODO add your handling code here:
        loadPasta();
    }//GEN-LAST:event_btnpastaActionPerformed

    private void btnchickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchickenActionPerformed
        // TODO add your handling code here:
        loadChicken();
    }//GEN-LAST:event_btnchickenActionPerformed

    private void btnwhatsnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnwhatsnewActionPerformed
        // TODO add your handling code here:
        loadWhatsNew();
    }//GEN-LAST:event_btnwhatsnewActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Welcome().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnViewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOrderActionPerformed
        // TODO add your handling code here:
        Summary summary = new Summary(cart, conn);
        summary.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnViewOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new SelectOrder("Dine In", new Cart("Dine In")).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel band;
    private javax.swing.JButton btnViewOrder;
    private javax.swing.JButton btnaddons;
    private javax.swing.JButton btnburger;
    private javax.swing.JButton btnchicken;
    private javax.swing.JButton btndessert;
    private javax.swing.JButton btndrink;
    private javax.swing.JButton btnpasta;
    private javax.swing.JButton btnwhatsnew;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblCategory1;
    private javax.swing.JLabel lblCategory2;
    private javax.swing.JLabel lblCategory3;
    private javax.swing.JLabel lbllogo2;
    private javax.swing.JPanel panelCategories;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JScrollPane panelScroll;
    private javax.swing.JLabel steplbl;
    private javax.swing.JLabel steplbl2;
    // End of variables declaration//GEN-END:variables
}
